/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/flights/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Busca ofertas de voo
         * @description Consulta a cadeia de providers em ordem e devolve as ofertas normalizadas.
         *     Resultados são cacheados por 5 minutos por combinação de critérios.
         *
         *     Rate limit próprio: 20 requisições por minuto por usuário e por IP,
         *     porque cada chamada consome quota de API externa paga.
         */
        post: operations["searchFlights"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/airports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca aeroportos por nome, cidade ou código IATA
         * @description Consulta a tabela local `airports`. Não consome quota de provider externo —
         *     por isso o autocomplete pode chamar livremente a cada tecla digitada.
         */
        get: operations["searchAirports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria uma conta */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autentica e inicia a sessão
         * @description Requer que o cliente tenha chamado `GET /sanctum/csrf-cookie` antes.
         *     A resposta define o cookie de sessão httpOnly — nenhum token é devolvido no corpo.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerra a sessão e invalida o cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados do usuário autenticado */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os voos favoritados do usuário */
        get: operations["listFavorites"];
        put?: never;
        /** Favorita uma oferta */
        post: operations["createFavorite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites/{favorite}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove um favorito
         * @description Responde 404 — não 403 — quando o favorito pertence a outro usuário,
         *     para não revelar a existência do recurso.
         */
        delete: operations["deleteFavorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/searches/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Últimas buscas do usuário */
        get: operations["recentSearches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FlightSearchCriteria: {
            /**
             * @description Código IATA de origem
             * @example GRU
             */
            origin: string;
            /**
             * @description Código IATA de destino, diferente da origem
             * @example LIS
             */
            destination: string;
            /**
             * Format: date
             * @description Data de ida, hoje ou futura
             * @example 2026-10-15
             */
            departure_date: string;
            /**
             * Format: date
             * @description Data de volta. Ausente ou nulo significa somente ida.
             * @example 2026-10-28
             */
            return_date?: string | null;
            /** @default 1 */
            adults: number;
            /** @default 0 */
            children: number;
            cabin?: components["schemas"]["CabinClass"];
            /**
             * @default BRL
             * @example BRL
             */
            currency: string;
        };
        /**
         * @default economy
         * @enum {string}
         */
        CabinClass: "economy" | "premium_economy" | "business" | "first";
        FlightOffer: {
            /** @description Identificador da oferta, estável dentro do TTL do cache */
            id: string;
            /**
             * Format: float
             * @example 3847.9
             */
            price: number;
            /** @example BRL */
            currency: string;
            seats_remaining: number | null;
            cabin?: components["schemas"]["CabinClass"];
            /** @description Um item para somente ida, dois para ida e volta */
            itineraries: components["schemas"]["Itinerary"][];
        };
        Itinerary: {
            /** @description Duração total incluindo conexões */
            duration_minutes: number;
            segments: components["schemas"]["Segment"][];
        };
        Segment: {
            origin: string;
            destination: string;
            /**
             * Format: date-time
             * @description ISO 8601 com offset do fuso local do aeroporto de origem
             */
            departure_at: string;
            /** Format: date-time */
            arrival_at: string;
            /** @example TP */
            carrier_code: string;
            /** @example TAP Air Portugal */
            carrier_name?: string | null;
            /** @example 1234 */
            flight_number: string;
            /** @example Airbus A330 */
            aircraft?: string | null;
            duration_minutes: number;
        };
        SearchMeta: {
            /**
             * @description Qual provider da cadeia respondeu. Útil em depuração.
             * @enum {string}
             */
            provider: "skyscanner" | "duffel" | "fake";
            /** @description Se a resposta veio do cache em vez de chamada externa */
            cached: boolean;
            total: number;
            /** @example BRL */
            currency?: string;
        };
        Airport: {
            /** @example GRU */
            iata_code: string;
            /** @example Aeroporto Internacional de São Paulo/Guarulhos */
            name: string;
            /** @example São Paulo */
            city: string;
            /** @example BR */
            country_code: string;
            /** @example America/Sao_Paulo */
            timezone?: string | null;
        };
        User: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
        };
        Favorite: {
            /** Format: uuid */
            id: string;
            offer: components["schemas"]["FlightOffer"];
            /** Format: date-time */
            created_at: string;
        };
        RecentSearch: {
            /** Format: uuid */
            id: string;
            criteria: components["schemas"]["FlightSearchCriteria"];
            /** Format: date-time */
            searched_at: string;
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "VALIDATION_FAILED" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "RATE_LIMITED" | "PROVIDERS_UNAVAILABLE";
                /** @description Mensagem em português, segura para exibir ao usuário */
                message: string;
                /** @description Erros por campo na validação; vazio nos demais casos */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description Usuário autenticado */
        AuthenticatedUser: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data: components["schemas"]["User"];
                };
            };
        };
        /** @description Dados inválidos */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_FAILED",
                 *         "message": "Verifique os campos destacados.",
                 *         "details": {
                 *           "destination": [
                 *             "O destino deve ser diferente da origem."
                 *           ]
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Sessão ausente ou expirada */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Recurso inexistente ou de outro usuário */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Limite de requisições excedido */
        RateLimited: {
            headers: {
                /** @description Segundos até poder tentar de novo */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Todos os providers da cadeia falharam. A mensagem nunca revela qual
         *     fornecedor falhou nem por quê — esse detalhe fica no log.
         */
        ProvidersUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "PROVIDERS_UNAVAILABLE",
                 *         "message": "Não foi possível consultar voos no momento. Tente novamente em instantes.",
                 *         "details": {}
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchFlights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlightSearchCriteria"];
            };
        };
        responses: {
            /** @description Ofertas encontradas (pode ser lista vazia) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FlightOffer"][];
                        meta: components["schemas"]["SearchMeta"];
                    };
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["ProvidersUnavailable"];
        };
    };
    searchAirports: {
        parameters: {
            query: {
                /**
                 * @description Termo de busca (mínimo 2 caracteres)
                 * @example guarul
                 */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aeroportos correspondentes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Airport"][];
                    };
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: email */
                    email: string;
                    /** @description Mínimo de 12 caracteres, verificada contra vazamentos conhecidos */
                    password: string;
                    password_confirmation: string;
                };
            };
        };
        responses: {
            201: components["responses"]["AuthenticatedUser"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            200: components["responses"]["AuthenticatedUser"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão encerrada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AuthenticatedUser"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    listFavorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favoritos do usuário autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Favorite"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    createFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    offer: components["schemas"]["FlightOffer"];
                };
            };
        };
        responses: {
            /** @description Favorito criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Favorite"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                favorite: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    recentSearches: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Buscas recentes, da mais nova para a mais antiga */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RecentSearch"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
}
